name: Conventional Request
description: Conventional Commit 스타일로 작업 요청을 등록합니다.
title: "feat: 작업 요약을 작성하세요"
labels:
  - triage
body:

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: 변경 범위를 선택하세요.
      options:
        - frontend
        - backend
        - ai
        - monorepo
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: Summary
      description: 한 줄로 핵심 목적을 적어주세요.
      placeholder: 로그인 버튼의 로딩 상태를 개선한다
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Background
      description: 왜 이 작업이 필요한지 배경과 문제를 작성하세요.
      placeholder: |
        - 현재 상태:
        - 문제점:
        - 기대 효과:
    validations:
      required: true
