name: Conventional Request
description: Conventional Commit 스타일로 작업 요청을 등록합니다.
title: "[request] "
labels:
  - triage
body:
  - type: markdown
    attributes:
      value: |
        ## 작성 안내
        - 이 폼은 Conventional Commits 형식을 따릅니다.
        - 권장 형식: `type(scope): summary`
        - 참고: https://www.conventionalcommits.org/en/v1.0.0/

  - type: dropdown
    id: commit_type
    attributes:
      label: Commit Type
      description: 요청 작업의 커밋 타입을 선택하세요.
      options:
        - feat
        - fix
        - refactor
        - chore
        - docs
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: 변경 범위를 선택하세요.
      options:
        - frontend
        - backend
        - ai
        - monorepo
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: Summary
      description: 한 줄로 핵심 목적을 적어주세요.
      placeholder: 로그인 버튼의 로딩 상태를 개선한다
    validations:
      required: true

  - type: input
    id: cc_title
    attributes:
      label: Conventional Title
      description: "`type(scope): summary` 형식으로 작성하세요."
      placeholder: "feat(frontend): add loading state to login button"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Background
      description: 왜 이 작업이 필요한지 배경과 문제를 작성하세요.
      placeholder: |
        - 현재 상태:
        - 문제점:
        - 기대 효과:
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: TODO
      description: 구현 작업을 체크리스트로 작성하세요.
      placeholder: |
        - [ ] API/로직 변경
        - [ ] UI/문서 반영
        - [ ] 테스트 또는 검증
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: 완료 판단 기준을 구체적으로 작성하세요.
      placeholder: |
        - [ ] 조건 A가 만족된다.
        - [ ] 조건 B가 만족된다.
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References (Optional)
      description: 관련 링크, 이슈, 문서가 있으면 추가하세요.
      placeholder: |
        - 관련 이슈:
        - 관련 PR:
        - 참고 문서:
